### ISSUE TITLE
Allow user to add notes to specific dates

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#1074]
## Description

Loop currently allows the user to add notes to habits as a whole. This task is to allow users to add notes to particular days. 

## Proposed workflow

The proposed workflow below is based on some earlier discussions with @aulia-adil (in #1014). Comments and suggestions are welcome.

- To add notes, the user would need to short press a particular date. The app would then display a dialog, containing a textarea, which allows the user to enter the notes and save them. Days that have notes receive an indicator dot in the main screen and in the calendar (see mockups below). Reading notes can be done by bringing up the dialog; no special UI is required.
- The message "*press and hold to check or uncheck*" (currently displayed when short pressing) would be removed. Long pressing would still toggle the checkmark directly, without bringing up the dialog. For users that have "toggle with short press" enabled, these two actions would be reversed: a short press would toggle the checkmark, while a long press would show the dialog.
- For numeric habits, we already have a dialog that allows the user to enter numbers. Instead of creating a new dialog for notes, we should just add a textarea to the existing dialog. This combined dialog could be showed both on short press and long press. The dialog for yes/no habits could also be improved over time.
- `HistoryChart` currently only accepts short presses, and either toggles the checkmarks directly (for yes/no habits) or displays a dialog (for numeric habits). We would need to modify `HistoryChart` so that it follows the same rules above: short press displays the dialog and long press shows the dialog.

## Subtasks

- [ ] Add a `notes` column to the `Repetitions` table.
- [ ] Add a `notes` field to `EntryRecord` and `Entry`
- [ ] Implement the dialog for Yes/No habits
- [ ] Implement the dialog for Numeric habits
- [ ] Show the dialog in `ListHabitsActivity`
- [ ] Show the dialog in `HistoryEditorDialog`
- [ ] Make `CheckmarkButtonView` and `NumberButtonView` display the notes indicator
- [ ] Make  `HistoryChart` display the notes indicator
- [ ] Make `HistoryChart` react differently to short and long press

### Dialogs

TODO

### `CheckmarkButtonView` and `NumberButtonView`
<a href="https://user-images.githubusercontent.com/4699657/126044763-b7d23fc9-ed9b-43c0-85cd-d2efe6fdfdf6.png"><img src="https://user-images.githubusercontent.com/4699657/126044763-b7d23fc9-ed9b-43c0-85cd-d2efe6fdfdf6.png" width=250px></a> <a href="https://user-images.githubusercontent.com/4699657/126044764-c43d2c87-952a-4080-87b0-5af077345097.png"><img src="https://user-images.githubusercontent.com/4699657/126044764-c43d2c87-952a-4080-87b0-5af077345097.png" width=250px></a>

### `HistoryChart`
<a href="https://user-images.githubusercontent.com/4699657/126044770-b5eaae5c-4f78-48d9-9a30-ca7559bd7594.png"><img src="https://user-images.githubusercontent.com/4699657/126044770-b5eaae5c-4f78-48d9-9a30-ca7559bd7594.png" width=250px></a> <a href="https://user-images.githubusercontent.com/4699657/126044771-3cdde2f4-14ab-49e8-9b8a-cad0e1da0dc9.png"><img src="https://user-images.githubusercontent.com/4699657/126044771-3cdde2f4-14ab-49e8-9b8a-cad0e1da0dc9.png" width=250px></a> <a href="https://user-images.githubusercontent.com/4699657/126044783-f47e0f60-0f21-4833-bf6d-610f690e0cb9.png"><img src="https://user-images.githubusercontent.com/4699657/126044783-f47e0f60-0f21-4833-bf6d-610f690e0cb9.png" width=250px></a> <a href="https://user-images.githubusercontent.com/4699657/126044779-706e68eb-49a8-4bf0-97cc-5b188bdbf723.png"><img src="https://user-images.githubusercontent.com/4699657/126044779-706e68eb-49a8-4bf0-97cc-5b188bdbf723.png" width=250px></a>

## Related discussions
- #194 
- #1014

**Comment by KristianTashkov** [comment]
> To add notes, the user would need to short press a particular date. The app would then display a dialog, containing a textarea, which allows the user to enter the notes and save them.

@iSoron do you envision this dialog to only contain the notes text area? One of the few changes that I still have in my local version different from master is a dialog option that allows you select directly the entry type for `YES_NO` habits, instead of having to cycle through long presses. Having it makes it more consistent with the numerical habit dialog that has both something to add an entry and a note in the same dialog, cc: @vbh

**Comment by iSoron** [comment]
@KristianTashkov We can have one dialog for everything.
