### ISSUE TITLE
Move custom views to uhabits-core

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#1076]
## Description

To make Loop Habit Tracker available on iOS and the web, we need to be able to render custom views in multiple platforms. Currently, we already have a multiplatform canvas implementation in `org.isoron.platform.gui.Canvas` (in `uhabits-core`). While a few custom views are already using this multiplatform implementation (including `BarChart` and `HistoryChart`), most of our custom view still rely directly on `android.graphics`.

This task is to migrate all remaining custom views to our multiplatform canvas, and remove all direct references to `android.graphics`.

## Notes

1. We already have some partial implementations (not currently used) in `org.isoron.uhabits.core.ui.views`, including `CheckmarkButton`, `NumberButton` and `Ring`. These implementations need to be finished.

## Subtasks

- [ ] `activities/common/views/FrequencyChart.kt`
- [ ] `activities/common/views/RingView.kt`
- [ ] `activities/common/views/ScoreChart.kt`
- [ ] `activities/common/views/StreakChart.kt`
- [ ] `activities/common/views/TargetChart.kt`
- [ ] `activities/habits/list/views/CheckmarkButtonView.kt`
- [ ] `activities/habits/list/views/HeaderView.kt`
- [ ] `activities/habits/list/views/NumberButtonView.kt`
