### ISSUE TITLE
Make large tests compatible with all supported Android API levels

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#886]
## Description

Starting in b561dfe, GitHub Actions now automatically runs all medium and large Android instrumented tests for every commit and pull request in our repository. Unfortunately, most of our large tests were written for API 28 and fail on lower API levels. This task is to make our large tests compatible API levels 23, 24, ..., 27, so that GitHub Actions can test the application on all supported Android versions.

Note that we do not currently test APIs 29, 30 or 31 either due to [severe stability issues with the emulator](https://issuetracker.google.com/issues/159732638) or because no open-source system images are available.

## Subtasks

- [x] Android 6.0 Marshmallow (API 23) 
- [x] Android 7.0 Nougat (API 24) 
- [x] Android 7.1 Nougat (API 25) 
- [x] Android 8.0 Oreo (API 26) 
- [x] Android 8.1.0 Oreo (API 27) 
- [x] Android 9 Pie (API 28) 
- [x] ~~Android 10 (API 29)~~ ([emulator crashes constantly](https://issuetracker.google.com/issues/159732638))
- [x] ~~Android 11 (API 30)~~ (open-source system image not available)
- [x] ~~Android 12 (API 31)~~ (open-source system image not available)

**Comment by iSoron** [comment]
Fixed in recent commits. Some tests are still somewhat flaky, so, as a workaround, we currently run the tests 3 times before failing them. PRs to make the tests less flaky are still very welcome.
